In [1]:
import numpy as np

In [70]:
a=np.random.random((2,3,5,1))

In [80]:
b=np.random.random((1,5))

In [81]:
a,b

(array([[[[0.6791541 ],
          [0.98309934],
          [0.10780482],
          [0.54991685],
          [0.46844212]],
 
         [[0.3204061 ],
          [0.90617221],
          [0.84686495],
          [0.18976674],
          [0.2816183 ]],
 
         [[0.36796154],
          [0.39876124],
          [0.42289557],
          [0.62169692],
          [0.04619268]]],
 
 
        [[[0.99345434],
          [0.22857974],
          [0.29900936],
          [0.67369983],
          [0.37004961]],
 
         [[0.39878958],
          [0.57209805],
          [0.08600428],
          [0.98248443],
          [0.68996587]],
 
         [[0.48842028],
          [0.52819123],
          [0.96526737],
          [0.87800457],
          [0.3535111 ]]]]),
 array([[0.92851706, 0.44797334, 0.37560674, 0.09177655, 0.95531808]]))

In [82]:
c=np.dot(a,b)

In [83]:
c.shape

(2, 3, 5, 5)

In [69]:
c

array([[[2.50725245, 1.65288166, 2.53476961],
        [1.71695023, 1.07187017, 1.12317422],
        [1.96597967, 1.43988053, 1.97498627]],

       [[1.54497082, 1.04276193, 1.80625593],
        [2.03907234, 1.17991545, 1.82563263],
        [1.86920166, 1.02168381, 1.5521103 ]]])